---
title: "Contribute"
author: "Thomas Rose"
date: "3 7 2021"
output:  md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)
```

Many thanks for your efforts in extending GlobaLID! 

# To prepare your submission

To facilitate the extension of GlobaLID, please make sure to use [this template](../www/template_contribute.csv) (UTF-8 encoded, comma-separated) and to follow these notations:

* Names and titles in local script are provided in square brackets after the transliterated names wherever possible, e.g. `Egypt [مصر]` or `Zamthang County [壤塘县]`. This also holds true for names with letters close to the English alphabet, like `Hunsruck [Hunsrück]` or `Cevennes [Cévennes]`.
* Multiple items within a field are separated by a `;` (semicolon), e.g. `Cu; Fe; Pb`. 
* Mineral names are never abbreviated. 
* Coordinates must be given in decimal degree according to EPSG 4326, these are the coordinates you get from e.g. GoogleMaps and OpenStreetMap.  

#### The submission workflow

1. Upload your data. Please make sure it is encoded in UTF-8 to avoid any problems with non-standard latin letters. 
2. Provide the correct information to parse your dataset (separator, decimal sign, quote). 
4. Fill in all other fields. They will depend on the type of the contribution: 
    + "New data": 
      - Published material: Please provide a pdf of the original publication, its DOI (if available, otherwise "n/a") and its full citation. 
      - Unpublished material: We ask for compliance with the guidelines for good scientific practice. Do not upload unpublished material of others. For uploading own unpublished data, please download [this declaration](), fill it out and upload it. Fill in "n/a" in the field of the doi and for the full citation. Without a correctly filled declaration your submission will be deleted without further consideration! 
    + "Update data": 
      - No further information is necessary. 
5. Please provide a short comment about the data, i. e. indicate what you updated, from which region the new data are etc. Please indicate here also any potential problems and ambiguities in the data. This will allow us to better organise the integration of your contribution into GlobaLID. 
6. Check in the tab "Data Viewer" if your data was correctly parsed. Double-check if everything is correct; typos must be avoided at all cost. 
7. Go to the "Check & Submit" tab and check if your submission is in agreement with the list. If so, tick the boxes. 
8. Finally, hit the "Submit" button. GlobaLID will roughly check your submission. 
    + You will get a confirmation of your submission if it was successful. 
    + If it was not successful, an error message will tell you which problem occurred. 
