---
title: "News"
author: "Thomas Rose"
date: "28 2 2021"
output:  md_document
always_allow_html: true

---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(kableExtra)

```

## News

2025-07-28 -- Additional data from Italy (R. Elsasser). The database now includes 5670 entries. A template for uploading data is now available through a link above the file upload. Version 1.1 of the web application is released. 

2025-04-26 -- Additional data from the Ural Mountains, some data from the Southern Levant corrected (R. Elsasser). The database now includes 5662 entries.

2025-03-04 -- Additional data from the Southern Levant (contributors: D. Finn, R. Elsasser). The database now includes 5589 entries.

2025-01-31 -- Additional data from the Alps (contributor: R. Elsasser) and Romania (contributor: K. J. Westner). The database now includes 5413 entries. 

2024-07-20 -- Additional data from many Central American Countries and several Southern European Countries (contributor: K. J. Westner). The database now includes 4623 entries. 

Coordinates and mining regions for some data from Chilean and German deposits were cleaned up.  

2024-03-31 -- Additional data from Chile (contributor: M. F. Becerra) and Germany (contributors: S. Fischer-Lechner, T. Rose). The database now includes 4563 entries. 

2024-01-03 -- The database version 1.1. is now published at GFZ Data Services, archiving its current state: <https://doi.org/10.5880/fidgeo.2023.043>

2023-11-19 -- Additional data from Argentina (contributor: M. F. Becerra). The database now includes 4147 entries. 

Additional metadata are included for some publications (contributor: K. J. Westner). Some minor editing was done on a few entries to increase consistency of the database (esp. unification of British vs. American English and capialisation)

The template for contributions was updated to the current metadata scheme. 

2023-08-20 -- Data can be subset now according to "Tectonic/geolog. super unit", "Tectonic/geolog. unit", "Tectonic/geolog. subunit", "Deposit type". Please check our <a href="https://doi.org/10.5880/fidgeo.2021.031" target="_blank">data description of the database</a> for how they are defined. 

2023-06-18 -- Additional data from 

* Germany (contributor: S. Fischer-Lechner, T. Rose)
* Sub-Sahara Africa (contributor: J. Stephens)

The database now includes 4046 entries. 

2023-06-04 -- Additional data from 

* Germany, Czechia (contributor: S. Fischer-Lechner, T. Rose)
* Greece (contributor: K. J. Westner, M. Vaxevanopoulos) 
* Bosnia and Herzegovina, Bulgaria, Kosovo, Montenegro, North Macedonia, Serbia (contributor: K. J. Westner). 

The database now includes 3245 entries.

2023-01-31 -- Additional data from Germany included (contributor: S. Fischer-Lechner. T. Rose). The database now includes 2763 entries.

2022-12-20 -- Additional data from Germany included (contributors: S. Fischer-Lechner, T. Rose). The database now includes 2699 entries. 

2022-03-28 -- The original publications for some data published in OXALID was added.

2022-03-23 -- Video tutorial for the GlobaLID web application is now available <a href="https://www.youtube.com/watch?v=qwKStMc-068" target="_blank">on YouTube</a>.

2022-03-01 -- New publication about GlobaLID: Klein, S., Rose, T., Westner, K. J., & Hsu, Y.-K. (2022). From OXALID to GlobaLID: Introducing a modern and FAIR lead isotope database with an interactive application. Archaeometry 64(4), 935--950. <a href="https://doi.org/10.1111/arcm.12762" target="_blank">https://doi.org/10.1111/arcm.12762</a>

2022-01-18 -- Additional data from Bosnia and Herzegovina, Bulgaria, Greece, and the Kosovo included (contributor: K. J. Westner). The database now includes 2468 entries. 

2021-11-27 -- Links open now in new tabs and do close the app anymore. Exception: Links that are displayed as their URL. In these cases automatic link detection overwrites it to the default behaviour (open in same tab).

2021-11-15 -- Additional data from Bulgaria included (contributor: K. J. Westner). The database now includes 2237 entries. 

2021-11-01 -- Additional data from Greece included (contributor: K. J. Westner). The database now includes 2141 entries. 

### Release of GlobaLID web application V. 1.0

2021-11-01 -- Version 1.0 of the GlobaLID web application is now online! 

### Release of GlobaLID database V. 1.0

2021-10-06 -- Version 1.0 of the GlobaLID database is now available at [https://doi.org/10.5880/fidgeo.2021.031](https://doi.org/10.5880/fidgeo.2021.031){target="_blank"}!  
The database currently includes 1892 entries, many of them are the result of hard work by Katrin J. Westner (Sardinia, Southeastern Europe, Greece) and Nima Nezafati (Iran). 

